# Your Website Title
title: Techbend

# Your Website URL
url: 'http://techbend.github.io'

# Leave it default
baseurl: '' 

# Google Analytics
ga_index: UA-XXXXXXXX-X
ga_cv: UA-XXXXXXXX-X

# Index page and Profile Information
name: Ali Tavallie
tagline: Software Developer, IoT, Reverse Engineering
pic: profile.png # profile.png can be found at /assets/images/profile.png
description: Full Stack Developer, IoT, Reverse Engineering
# description_tiny: 'Home: +60-4 | Studied: +1-408 | Work: +60-3'
email: you.email.email@gmail.com
website: http://techbend.github.io # do not add http://
linkedin: tavallaie
github: tavallaie
# twitter: '@realmelvinchng'

# Files or folders to be excluded
exclude: [gitbook_source_code/]

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap
